### ISSUE TITLE
Timer offline always. 

### ISSUE THREAD

**Issue by Root-MtX** [KurtSanders/STOrbitBhyveController#2]
My timer device always shows offline even when the b-hyve app is connected to it. Does this require the wifi hub to be operational?

**Comment by KurtSanders** [comment]
Are you connecting to your b•hyve™ timer device via Bluetooth or WiFi?

**Comment by Root-MtX** [comment]
Bluetooth through the bhyve app

**Comment by KurtSanders** [comment]
The Online/Offline refers to WiFi using their hub

**Comment by Root-MtX** [comment]
Figured that was the case, thanks for the clarification

**Comment by jackc88** [comment]
Kurt:  Thank You for the work.  Mine is connected via WiFi Hub.  The timer shows active but offline and no events.  I only see"lastSTupdate: Cloud Refresh Requested" when click on refreshing from the ST app.  Is there something I should check?

` error java.lang.NullPointerException: Cannot get property 'next_start_time' on null object @line 239 (doCall)`

I do have a traditional program configured for the timer.

**Comment by KurtSanders** [comment]
> Kurt: Thank You for the work. Mine is connected via WiFi Hub. The timer shows active but offline and no events. I only see"lastSTupdate: Cloud Refresh Requested" when click on refreshing from the ST app. Is there something I should check?
> 
> ` error java.lang.NullPointerException: Cannot get property 'next_start_time' on null object @line 239 (doCall)`
> 
> I do have a traditional program configured for the timer.

Dear Jackc88,

I'm not sure why you are getting this error and missing data, but we can try a view things.

1. Can you verify your b•hyve™ device settings at [Orbit Support Dashboard](https://techsupport.orbitbhyve.com/).  You will need to login to see your devices data. 
2. After this check to verify that your b•hyve™ device is showing all the data, I might have to privately obtain your b•hyve™ credentials to debug.  We can trade emails so we can proceed.
