### ISSUE TITLE
Lost connection to Web Socket: status: closing, will reconnect -- spamming logs

### ISSUE THREAD

**Issue by apwelsh** [KurtSanders/STOrbitBhyveController#5]
My hubitat sprinkler controller seems to be working fine, but every 30 minutes, all my zones report this in the log.  I have all logging turned off.  Not sure if this is normal behavior, and would like to have this silenced in the logs if it is normal, or help on resolving this if it isn't normal.

**Comment by KurtSanders** [comment]
@apwelsh 

You should be using https://github.com/dcmeglio/hubitat-orbitbhyve for Orbit-Hubitat integration, and if so, you need to move this issue to that repo.

**Comment by apwelsh** [comment]
The one I installed from Hubitat package manager does. It have a url,  it it has your name.  How do I know which one HPM installed?

**Comment by KurtSanders** [comment]
I would remove the one that is currently installed in HE and start a new install with HPM using a keyword search of 'orbit' and look for the one by Dominick Meglio.

![image](https://user-images.githubusercontent.com/12133562/118309815-cb710d80-b4bb-11eb-96fd-72dff95f6834.png)

**Comment by apwelsh** [comment]
Oh, I think I misread your comment.  I read it as this integration on your site is available via HPM.  I will read out to the other developer. Thank you

**Comment by KurtSanders** [comment]
No problem.  As I stated, my rough port from SmartThings to HE is not as robust or stable as the one that is currently in HPM that was based on my work but enhanced by Dominick.  

Dominick did an outstanding job of adding Orbit command and control via HE's webhook integration.  So if you install that version via HPM, perhaps your log errors will be eliminated, if not and you have his port installed, then you can contact him via his GitHub or the HE community thread I listed above!
